export enum NotificationType {
    ORDER_PLACED = 'ORDER_PLACED',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    SHIPMENT_STATUS = 'SHIPMENT_STATUS',
    GENERAL = 'GENERAL',
    ADMIN_NOTIFICATION = 'ADMIN_NOTIFICATION',
}
